name: Deploy Site

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: TravisSpomer/deploy-to-azure-storage@v1.5.0
        with:
          source-path: site
          sas-url: ${{ secrets.AZURE_STORAGE_SAS_URL }}
